/*
 * Copyright 2016, Cypress Semiconductor
 * All Rights Reserved.
 *
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Cypress Semiconductor;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Cypress Semiconductor.
 */

#pragma once

#include <Windows.h>
#include "mbt.h"

// The base of the IOCTL control codes.
#define BTWUSB_IOCTL_INDEX  0x089a

#define IOCTL_BTWUSB_GET_PIPE_INFO     CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_DEVICE_DESCRIPTOR CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+1,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_CONFIGURATION_DESCRIPTOR CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+2,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_PUT CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+3,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_PUT_CMD CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+4,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+5,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_EVENT CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+6,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_STATS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+7,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_CLEAR_STATS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+8,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_VERSION CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+9,METHOD_BUFFERED, FILE_ANY_ACCESS)

// TMP!!
#define IOCTL_BTWUSB_CANCEL_READ CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xA,METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_BTWUSB_SUBMIT_READ CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xB,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_RESET_PORT CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xC,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_IDS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xD,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GO_DFU CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xE,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_UNCOND_SUSPEND CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0xF,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_COND_SUSPEND CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x10,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_HARDWARE_ID CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x11,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_DEVICE_DESC CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x12,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_SET_VOICE CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x13,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_PUT_VOICE CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x14,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_VOICE CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x15,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_SET_EXCLUSIVE_ACCESS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x16,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_RESET_EXCLUSIVE_ACCESS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x17,METHOD_BUFFERED, FILE_ANY_ACCESS)

// #define IOCTL_BTWUSB_SET_VOICE_16BIT CTL_CODE(FILE_DEVICE_UNKNOWN,  \
//    BTWUSB_IOCTL_INDEX+0x18,METHOD_BUFFERED, FILE_ANY_ACCESS)
//
#define IOCTL_BTWUSB_IS_VOICE_AVAILABLE CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x19,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_ADD_VOICE_CHANNEL CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1A,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_REMOVE_VOICE_CHANNEL CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1B,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_ENTER_SEL_SUSPEND CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1C,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_CANCEL_SEL_SUSPEND CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1D,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_STATUS CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1E,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_SET_REMOTE_WAKEUP_IN_SUSPEND CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x1F,METHOD_BUFFERED, FILE_ANY_ACCESS)

//
// Broadcom diagnostic interface related requests
//
#define IOCTL_BTWUSB_IS_BRCM_DIAG_AVAILABLE CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x20,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_PUT_DIAG CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x21,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_DIAG CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x22,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_SET_PRIORITY CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x23,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_PRIORITY CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x24,METHOD_BUFFERED, FILE_ANY_ACCESS)


#define IOCTL_BTWUSB_GET_SERIAL_NUMBER CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x25,METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_BTWUSB_GET_PDO_NAME CTL_CODE(FILE_DEVICE_UNKNOWN,  \
    BTWUSB_IOCTL_INDEX+0x26,METHOD_BUFFERED, FILE_ANY_ACCESS)


//
// USB Bus class, use this class to read/write from/to the USB bus device
//
class UsbHelper : public TransportHelper
{
public:
    UsbHelper();
    virtual ~UsbHelper();

    // open BTWUSB driver to access device
    BOOL OpenPort(char* argv);

    BOOL ClosePort();

    // read data from device
    DWORD Read(LPBYTE b, DWORD dwLen);

    // write data to device
    DWORD Write(LPBYTE b, DWORD dwLen);

    void Flush(DWORD dwFlags);
};

