/*
 * This file has been automatically generated by the WICED BT Designer
 * Definitions for constants used in the device's GATT database and function
 * prototypes that can be used to send notifications
 *
 */
